export const PROVINCES = [
  { code: '10', nameTh: 'กรุงเทพมหานคร' },
  { code: '11', nameTh: 'สมุทรปราการ' },
  { code: '12', nameTh: 'นนทบุรี' },
  { code: '13', nameTh: 'ปทุมธานี' },
  { code: '14', nameTh: 'พระนครศรีอยุธยา' },
  { code: '15', nameTh: 'อ่างทอง' },
  { code: '16', nameTh: 'ลพบุรี' },
  { code: '17', nameTh: 'สิงห์บุรี' },
  { code: '18', nameTh: 'ชัยนาท' },
  { code: '19', nameTh: 'สระบุรี' },
  { code: '20', nameTh: 'ชลบุรี' },
  { code: '21', nameTh: 'ระยอง' },
  { code: '22', nameTh: 'จันทบุรี' },
  { code: '23', nameTh: 'ตราด' },
  { code: '24', nameTh: 'ฉะเชิงเทรา' },
  { code: '25', nameTh: 'ปราจีนบุรี' },
  { code: '26', nameTh: 'นครนายก' },
  { code: '27', nameTh: 'สระแก้ว' },
  { code: '30', nameTh: 'นครราชสีมา' },
  { code: '31', nameTh: 'บุรีรัมย์' },
  { code: '32', nameTh: 'สุรินทร์' },
  { code: '33', nameTh: 'ศรีสะเกษ' },
  { code: '34', nameTh: 'อุบลราชธานี' },
  { code: '35', nameTh: 'ยโสธร' },
  { code: '36', nameTh: 'ชัยภูมิ' },
  { code: '37', nameTh: 'อำนาจเจริญ' },
  { code: '38', nameTh: 'บึงกาฬ' },
  { code: '39', nameTh: 'หนองบัวลำภู' },
  { code: '40', nameTh: 'ขอนแก่น' },
  { code: '41', nameTh: 'อุดรธานี' },
  { code: '42', nameTh: 'เลย' },
  { code: '43', nameTh: 'หนองคาย' },
  { code: '44', nameTh: 'มหาสารคาม' },
  { code: '45', nameTh: 'ร้อยเอ็ด' },
  { code: '46', nameTh: 'กาฬสินธุ์' },
  { code: '47', nameTh: 'สกลนคร' },
  { code: '48', nameTh: 'นครพนม' },
  { code: '49', nameTh: 'มุกดาหาร' },
  { code: '50', nameTh: 'เชียงใหม่' },
  { code: '51', nameTh: 'ลำพูน' },
  { code: '52', nameTh: 'ลำปาง' },
  { code: '53', nameTh: 'อุตรดิตถ์' },
  { code: '54', nameTh: 'แพร่' },
  { code: '55', nameTh: 'น่าน' },
  { code: '56', nameTh: 'พะเยา' },
  { code: '57', nameTh: 'เชียงราย' },
  { code: '58', nameTh: 'แม่ฮ่องสอน' },
  { code: '60', nameTh: 'นครสวรรค์' },
  { code: '61', nameTh: 'อุทัยธานี' },
  { code: '62', nameTh: 'กำแพงเพชร' },
  { code: '63', nameTh: 'ตาก' },
  { code: '64', nameTh: 'สุโขทัย' },
  { code: '65', nameTh: 'พิษณุโลก' },
  { code: '66', nameTh: 'พิจิตร' },
  { code: '67', nameTh: 'เพชรบูรณ์' },
  { code: '70', nameTh: 'ราชบุรี' },
  { code: '71', nameTh: 'กาญจนบุรี' },
  { code: '72', nameTh: 'สุพรรณบุรี' },
  { code: '73', nameTh: 'นครปฐม' },
  { code: '74', nameTh: 'สมุทรสาคร' },
  { code: '75', nameTh: 'สมุทรสงคราม' },
  { code: '76', nameTh: 'เพชรบุรี' },
  { code: '77', nameTh: 'ประจวบคีรีขันธ์' },
  { code: '80', nameTh: 'นครศรีธรรมราช' },
  { code: '81', nameTh: 'กระบี่' },
  { code: '82', nameTh: 'พังงา' },
  { code: '83', nameTh: 'ภูเก็ต' },
  { code: '84', nameTh: 'สุราษฎร์ธานี' },
  { code: '85', nameTh: 'ระนอง' },
  { code: '86', nameTh: 'ชุมพร' },
  { code: '90', nameTh: 'สงขลา' },
  { code: '91', nameTh: 'สตูล' },
  { code: '92', nameTh: 'ตรัง' },
  { code: '93', nameTh: 'พัทลุง' },
  { code: '94', nameTh: 'ปัตตานี' },
  { code: '95', nameTh: 'ยะลา' },
  { code: '96', nameTh: 'นราธิวาส' },
] as const;

export type Province = (typeof PROVINCES)[number];
export type ProvinceCode = Province['code'];

const CODE_SET: ReadonlySet<string> = new Set(PROVINCES.map((p) => p.code));

export function isProvinceCode(value: string): value is ProvinceCode {
  return CODE_SET.has(value);
}

export function getProvinceName(code: ProvinceCode): string {
  const found = PROVINCES.find((p) => p.code === code);
  return found ? found.nameTh : code;
}